### ISSUE TITLE
Modified version

### ISSUE THREAD

**Issue by uname0x96** [dolongbien/HumanBehaviorBKU#11]
Hi @dolongbien ,
Can you give me some change you did in your implementation ? I found the original git for this paper here: "https://github.com/vantage-vision-vv/Anomaly-Detection-in-Surveillance-Videos".

Thank you in advance!

**Comment by dolongbien** [comment]
Hi, the above link is not the original git repo.2 changes: loss function and dataset, also

**Comment by dolongbien** [comment]
I made the mistake of clicking Comment before finishing it, so please disregard the previous one. 2 changes are the loss function and dataset, also from 32segments to 64segments.

**Comment by uname0x96** [comment]
@dolongbien Thanks for the reply. You changed the loss function and it makes your model better with Road_Accident dataset?

**Comment by uname0x96** [comment]
@dolongbien Did you try to use your project in real-time?

**Comment by ntdat017** [comment]
> @dolongbien Did you try to use your project in real-time?

Hi @cong235 , we just stop in prove the potential of accident detection model. To put in real-time, there are a lot of things have to do. We also hope somebody can make it in realtime.
