### ISSUE TITLE
 AttributeError: module 'theano' has no attribute 'tests'

### ISSUE THREAD

**Issue by cervantes-loves-ai** [dolongbien/HumanBehaviorBKU#6]
already tried after install "pip install nose". but can't solve this.

`Using Theano backend.

---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-32-45041235fa2f> in <module>()
----> 1 from keras.models import Sequential
      2 from keras.layers import Dense, Dropout, Activation, TimeDistributedDense ,LSTM,Reshape
      3 from keras.regularizers import l2
      4 from keras.optimizers import SGD,adam, Adagrad
      5 from scipy.io import loadmat, savemat

3 frames

/usr/local/lib/python3.6/dist-packages/theano/__init__.py in <module>()
     98 # needed during that phase.
     99 import theano.tests
--> 100 if hasattr(theano.tests, "TheanoNoseTester"):
    101     test = theano.tests.TheanoNoseTester().test
    102 else:

AttributeError: module 'theano' has no attribute 'tests'`

[https://drive.google.com/open?id=1a2JBxpTjYd_K7UhJXkQCYfJfso2jYHiM](url)

**Comment by dolongbien** [comment]
Hi,
This could be a conflict between Theano version and CUDA or GPU instance. There are some rules regarding this compatibility, you should do a few research on it. What are your CUDA version and GPU model on Google Colab?

**Comment by cervantes-loves-ai** [comment]
I solved it. thank you so much for your advice.
