### ISSUE TITLE
about extracting c3d features  

### ISSUE THREAD

**Issue by cervantes-loves-ai** [dolongbien/HumanBehaviorBKU#7]
is it possible to share your computed c3d features? 

thanks in advance.

**Comment by draxler1** [comment]
https://www.dropbox.com/s/af6kmpu6zwcuump/out-20190514T004829Z-001.zip?dl=0

Here you can download all files computed C3D features of CVPR Crime dataset used by that Waqas Sultani's work.

**Comment by dolongbien** [comment]
Thanks @draxler1. Take a look at the above link, it should work well on our training code @cervantes-loves-ai.
